### ISSUE TITLE
question about module ocean.speech

### ISSUE THREAD

**Issue by RulerOne** [Peidong-Wang/OCEAN#1]
Hello! Thanks for your open source. However, an error "ModuleNotFoundError: No module named 'ocean.speech'" occurred when import this module and I found there was no folder named "speech" in "ocean" directory. Can you tell me how to use it or fix it? I am looking forward to your reply. Thanks again!

**Comment by Peidong-Wang** [comment]
Have you installed the module using `python setup.py install`?

**Comment by Peidong-Wang** [comment]
Thanks for pointing it out! The error should be gone now.

**Comment by Peidong-Wang** [comment]
Thanks for pointing it out! The error should be gone now.

**Comment by Peidong-Wang** [comment]
Thanks for pointing it out! The error should be gone now.
